// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WechatProto.proto

package com.wx.frameWork.proto;

/**
 * <pre>
 * 请求消息结构体
 * </pre>
 *
 * Protobuf type {@code BaseMsg}
 */
public  final class BaseMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BaseMsg)
    BaseMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BaseMsg.newBuilder() to construct.
  private BaseMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BaseMsg() {
    ret_ = 0;
    cmd_ = 0;
    cmdUrl_ = "";
    shortHost_ = "";
    longHost_ = "";
    longHead_ = com.google.protobuf.ByteString.EMPTY;
    payloads_ = com.google.protobuf.ByteString.EMPTY;
    playloadextend_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BaseMsg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            ret_ = input.readInt32();
            break;
          }
          case 16: {

            cmd_ = input.readInt32();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            cmdUrl_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            shortHost_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            longHost_ = s;
            break;
          }
          case 50: {
            com.wx.frameWork.proto.User.Builder subBuilder = null;
            if (user_ != null) {
              subBuilder = user_.toBuilder();
            }
            user_ = input.readMessage(com.wx.frameWork.proto.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(user_);
              user_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {

            longHead_ = input.readBytes();
            break;
          }
          case 66: {

            payloads_ = input.readBytes();
            break;
          }
          case 74: {

            playloadextend_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wx.frameWork.proto.WechatProto.internal_static_BaseMsg_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wx.frameWork.proto.WechatProto.internal_static_BaseMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wx.frameWork.proto.BaseMsg.class, com.wx.frameWork.proto.BaseMsg.Builder.class);
  }

  public static final int RET_FIELD_NUMBER = 1;
  private int ret_;
  /**
   * <pre>
   * 状态码
   * </pre>
   *
   * <code>int32 ret = 1;</code>
   */
  public int getRet() {
    return ret_;
  }

  public static final int CMD_FIELD_NUMBER = 2;
  private int cmd_;
  /**
   * <pre>
   * 请求接口
   * </pre>
   *
   * <code>int32 cmd = 2;</code>
   */
  public int getCmd() {
    return cmd_;
  }

  public static final int CMDURL_FIELD_NUMBER = 3;
  private volatile Object cmdUrl_;
  /**
   * <pre>
   * 接口连接
   * </pre>
   *
   * <code>string cmdUrl = 3;</code>
   */
  public String getCmdUrl() {
    Object ref = cmdUrl_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      cmdUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 接口连接
   * </pre>
   *
   * <code>string cmdUrl = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCmdUrlBytes() {
    Object ref = cmdUrl_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      cmdUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHORTHOST_FIELD_NUMBER = 4;
  private volatile Object shortHost_;
  /**
   * <pre>
   * 短连接地址
   * </pre>
   *
   * <code>string shortHost = 4;</code>
   */
  public String getShortHost() {
    Object ref = shortHost_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      shortHost_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 短连接地址
   * </pre>
   *
   * <code>string shortHost = 4;</code>
   */
  public com.google.protobuf.ByteString
      getShortHostBytes() {
    Object ref = shortHost_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      shortHost_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LONGHOST_FIELD_NUMBER = 5;
  private volatile Object longHost_;
  /**
   * <pre>
   * 长链接地址
   * </pre>
   *
   * <code>string longHost = 5;</code>
   */
  public String getLongHost() {
    Object ref = longHost_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      longHost_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 长链接地址
   * </pre>
   *
   * <code>string longHost = 5;</code>
   */
  public com.google.protobuf.ByteString
      getLongHostBytes() {
    Object ref = longHost_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      longHost_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_FIELD_NUMBER = 6;
  private com.wx.frameWork.proto.User user_;
  /**
   * <pre>
   * 当前微信号结构体
   * </pre>
   *
   * <code>.User user = 6;</code>
   */
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <pre>
   * 当前微信号结构体
   * </pre>
   *
   * <code>.User user = 6;</code>
   */
  public com.wx.frameWork.proto.User getUser() {
    return user_ == null ? com.wx.frameWork.proto.User.getDefaultInstance() : user_;
  }
  /**
   * <pre>
   * 当前微信号结构体
   * </pre>
   *
   * <code>.User user = 6;</code>
   */
  public com.wx.frameWork.proto.UserOrBuilder getUserOrBuilder() {
    return getUser();
  }

  public static final int LONGHEAD_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString longHead_;
  /**
   * <pre>
   * 长连接包头
   * </pre>
   *
   * <code>bytes longHead = 7;</code>
   */
  public com.google.protobuf.ByteString getLongHead() {
    return longHead_;
  }

  public static final int PAYLOADS_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString payloads_;
  /**
   * <pre>
   * 数据
   * </pre>
   *
   * <code>bytes payloads = 8;</code>
   */
  public com.google.protobuf.ByteString getPayloads() {
    return payloads_;
  }

  public static final int PLAYLOADEXTEND_FIELD_NUMBER = 9;
  private com.google.protobuf.ByteString playloadextend_;
  /**
   * <pre>
   * 扩展数据
   * </pre>
   *
   * <code>bytes playloadextend = 9;</code>
   */
  public com.google.protobuf.ByteString getPlayloadextend() {
    return playloadextend_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ret_ != 0) {
      output.writeInt32(1, ret_);
    }
    if (cmd_ != 0) {
      output.writeInt32(2, cmd_);
    }
    if (!getCmdUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cmdUrl_);
    }
    if (!getShortHostBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, shortHost_);
    }
    if (!getLongHostBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, longHost_);
    }
    if (user_ != null) {
      output.writeMessage(6, getUser());
    }
    if (!longHead_.isEmpty()) {
      output.writeBytes(7, longHead_);
    }
    if (!payloads_.isEmpty()) {
      output.writeBytes(8, payloads_);
    }
    if (!playloadextend_.isEmpty()) {
      output.writeBytes(9, playloadextend_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ret_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ret_);
    }
    if (cmd_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, cmd_);
    }
    if (!getCmdUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cmdUrl_);
    }
    if (!getShortHostBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, shortHost_);
    }
    if (!getLongHostBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, longHost_);
    }
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getUser());
    }
    if (!longHead_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, longHead_);
    }
    if (!payloads_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, payloads_);
    }
    if (!playloadextend_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, playloadextend_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wx.frameWork.proto.BaseMsg)) {
      return super.equals(obj);
    }
    com.wx.frameWork.proto.BaseMsg other = (com.wx.frameWork.proto.BaseMsg) obj;

    boolean result = true;
    result = result && (getRet()
        == other.getRet());
    result = result && (getCmd()
        == other.getCmd());
    result = result && getCmdUrl()
        .equals(other.getCmdUrl());
    result = result && getShortHost()
        .equals(other.getShortHost());
    result = result && getLongHost()
        .equals(other.getLongHost());
    result = result && (hasUser() == other.hasUser());
    if (hasUser()) {
      result = result && getUser()
          .equals(other.getUser());
    }
    result = result && getLongHead()
        .equals(other.getLongHead());
    result = result && getPayloads()
        .equals(other.getPayloads());
    result = result && getPlayloadextend()
        .equals(other.getPlayloadextend());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RET_FIELD_NUMBER;
    hash = (53 * hash) + getRet();
    hash = (37 * hash) + CMD_FIELD_NUMBER;
    hash = (53 * hash) + getCmd();
    hash = (37 * hash) + CMDURL_FIELD_NUMBER;
    hash = (53 * hash) + getCmdUrl().hashCode();
    hash = (37 * hash) + SHORTHOST_FIELD_NUMBER;
    hash = (53 * hash) + getShortHost().hashCode();
    hash = (37 * hash) + LONGHOST_FIELD_NUMBER;
    hash = (53 * hash) + getLongHost().hashCode();
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    hash = (37 * hash) + LONGHEAD_FIELD_NUMBER;
    hash = (53 * hash) + getLongHead().hashCode();
    hash = (37 * hash) + PAYLOADS_FIELD_NUMBER;
    hash = (53 * hash) + getPayloads().hashCode();
    hash = (37 * hash) + PLAYLOADEXTEND_FIELD_NUMBER;
    hash = (53 * hash) + getPlayloadextend().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wx.frameWork.proto.BaseMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wx.frameWork.proto.BaseMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wx.frameWork.proto.BaseMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wx.frameWork.proto.BaseMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wx.frameWork.proto.BaseMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wx.frameWork.proto.BaseMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wx.frameWork.proto.BaseMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wx.frameWork.proto.BaseMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wx.frameWork.proto.BaseMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wx.frameWork.proto.BaseMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wx.frameWork.proto.BaseMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wx.frameWork.proto.BaseMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wx.frameWork.proto.BaseMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 请求消息结构体
   * </pre>
   *
   * Protobuf type {@code BaseMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BaseMsg)
      com.wx.frameWork.proto.BaseMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wx.frameWork.proto.WechatProto.internal_static_BaseMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wx.frameWork.proto.WechatProto.internal_static_BaseMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wx.frameWork.proto.BaseMsg.class, com.wx.frameWork.proto.BaseMsg.Builder.class);
    }

    // Construct using com.wx.frameWork.proto.BaseMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      ret_ = 0;

      cmd_ = 0;

      cmdUrl_ = "";

      shortHost_ = "";

      longHost_ = "";

      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      longHead_ = com.google.protobuf.ByteString.EMPTY;

      payloads_ = com.google.protobuf.ByteString.EMPTY;

      playloadextend_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wx.frameWork.proto.WechatProto.internal_static_BaseMsg_descriptor;
    }

    public com.wx.frameWork.proto.BaseMsg getDefaultInstanceForType() {
      return com.wx.frameWork.proto.BaseMsg.getDefaultInstance();
    }

    public com.wx.frameWork.proto.BaseMsg build() {
      com.wx.frameWork.proto.BaseMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.wx.frameWork.proto.BaseMsg buildPartial() {
      com.wx.frameWork.proto.BaseMsg result = new com.wx.frameWork.proto.BaseMsg(this);
      result.ret_ = ret_;
      result.cmd_ = cmd_;
      result.cmdUrl_ = cmdUrl_;
      result.shortHost_ = shortHost_;
      result.longHost_ = longHost_;
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      result.longHead_ = longHead_;
      result.payloads_ = payloads_;
      result.playloadextend_ = playloadextend_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wx.frameWork.proto.BaseMsg) {
        return mergeFrom((com.wx.frameWork.proto.BaseMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wx.frameWork.proto.BaseMsg other) {
      if (other == com.wx.frameWork.proto.BaseMsg.getDefaultInstance()) return this;
      if (other.getRet() != 0) {
        setRet(other.getRet());
      }
      if (other.getCmd() != 0) {
        setCmd(other.getCmd());
      }
      if (!other.getCmdUrl().isEmpty()) {
        cmdUrl_ = other.cmdUrl_;
        onChanged();
      }
      if (!other.getShortHost().isEmpty()) {
        shortHost_ = other.shortHost_;
        onChanged();
      }
      if (!other.getLongHost().isEmpty()) {
        longHost_ = other.longHost_;
        onChanged();
      }
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (other.getLongHead() != com.google.protobuf.ByteString.EMPTY) {
        setLongHead(other.getLongHead());
      }
      if (other.getPayloads() != com.google.protobuf.ByteString.EMPTY) {
        setPayloads(other.getPayloads());
      }
      if (other.getPlayloadextend() != com.google.protobuf.ByteString.EMPTY) {
        setPlayloadextend(other.getPlayloadextend());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wx.frameWork.proto.BaseMsg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wx.frameWork.proto.BaseMsg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int ret_ ;
    /**
     * <pre>
     * 状态码
     * </pre>
     *
     * <code>int32 ret = 1;</code>
     */
    public int getRet() {
      return ret_;
    }
    /**
     * <pre>
     * 状态码
     * </pre>
     *
     * <code>int32 ret = 1;</code>
     */
    public Builder setRet(int value) {
      
      ret_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 状态码
     * </pre>
     *
     * <code>int32 ret = 1;</code>
     */
    public Builder clearRet() {
      
      ret_ = 0;
      onChanged();
      return this;
    }

    private int cmd_ ;
    /**
     * <pre>
     * 请求接口
     * </pre>
     *
     * <code>int32 cmd = 2;</code>
     */
    public int getCmd() {
      return cmd_;
    }
    /**
     * <pre>
     * 请求接口
     * </pre>
     *
     * <code>int32 cmd = 2;</code>
     */
    public Builder setCmd(int value) {
      
      cmd_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求接口
     * </pre>
     *
     * <code>int32 cmd = 2;</code>
     */
    public Builder clearCmd() {
      
      cmd_ = 0;
      onChanged();
      return this;
    }

    private Object cmdUrl_ = "";
    /**
     * <pre>
     * 接口连接
     * </pre>
     *
     * <code>string cmdUrl = 3;</code>
     */
    public String getCmdUrl() {
      Object ref = cmdUrl_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cmdUrl_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 接口连接
     * </pre>
     *
     * <code>string cmdUrl = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCmdUrlBytes() {
      Object ref = cmdUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cmdUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 接口连接
     * </pre>
     *
     * <code>string cmdUrl = 3;</code>
     */
    public Builder setCmdUrl(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cmdUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接口连接
     * </pre>
     *
     * <code>string cmdUrl = 3;</code>
     */
    public Builder clearCmdUrl() {
      
      cmdUrl_ = getDefaultInstance().getCmdUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接口连接
     * </pre>
     *
     * <code>string cmdUrl = 3;</code>
     */
    public Builder setCmdUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cmdUrl_ = value;
      onChanged();
      return this;
    }

    private Object shortHost_ = "";
    /**
     * <pre>
     * 短连接地址
     * </pre>
     *
     * <code>string shortHost = 4;</code>
     */
    public String getShortHost() {
      Object ref = shortHost_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        shortHost_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 短连接地址
     * </pre>
     *
     * <code>string shortHost = 4;</code>
     */
    public com.google.protobuf.ByteString
        getShortHostBytes() {
      Object ref = shortHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        shortHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 短连接地址
     * </pre>
     *
     * <code>string shortHost = 4;</code>
     */
    public Builder setShortHost(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      shortHost_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 短连接地址
     * </pre>
     *
     * <code>string shortHost = 4;</code>
     */
    public Builder clearShortHost() {
      
      shortHost_ = getDefaultInstance().getShortHost();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 短连接地址
     * </pre>
     *
     * <code>string shortHost = 4;</code>
     */
    public Builder setShortHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      shortHost_ = value;
      onChanged();
      return this;
    }

    private Object longHost_ = "";
    /**
     * <pre>
     * 长链接地址
     * </pre>
     *
     * <code>string longHost = 5;</code>
     */
    public String getLongHost() {
      Object ref = longHost_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        longHost_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 长链接地址
     * </pre>
     *
     * <code>string longHost = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLongHostBytes() {
      Object ref = longHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        longHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 长链接地址
     * </pre>
     *
     * <code>string longHost = 5;</code>
     */
    public Builder setLongHost(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      longHost_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 长链接地址
     * </pre>
     *
     * <code>string longHost = 5;</code>
     */
    public Builder clearLongHost() {
      
      longHost_ = getDefaultInstance().getLongHost();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 长链接地址
     * </pre>
     *
     * <code>string longHost = 5;</code>
     */
    public Builder setLongHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      longHost_ = value;
      onChanged();
      return this;
    }

    private com.wx.frameWork.proto.User user_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wx.frameWork.proto.User, com.wx.frameWork.proto.User.Builder, com.wx.frameWork.proto.UserOrBuilder> userBuilder_;
    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     *
     * <code>.User user = 6;</code>
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     *
     * <code>.User user = 6;</code>
     */
    public com.wx.frameWork.proto.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? com.wx.frameWork.proto.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     *
     * <code>.User user = 6;</code>
     */
    public Builder setUser(com.wx.frameWork.proto.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     *
     * <code>.User user = 6;</code>
     */
    public Builder setUser(
        com.wx.frameWork.proto.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     *
     * <code>.User user = 6;</code>
     */
    public Builder mergeUser(com.wx.frameWork.proto.User value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            com.wx.frameWork.proto.User.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     *
     * <code>.User user = 6;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     *
     * <code>.User user = 6;</code>
     */
    public com.wx.frameWork.proto.User.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     *
     * <code>.User user = 6;</code>
     */
    public com.wx.frameWork.proto.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            com.wx.frameWork.proto.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <pre>
     * 当前微信号结构体
     * </pre>
     *
     * <code>.User user = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wx.frameWork.proto.User, com.wx.frameWork.proto.User.Builder, com.wx.frameWork.proto.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.wx.frameWork.proto.User, com.wx.frameWork.proto.User.Builder, com.wx.frameWork.proto.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private com.google.protobuf.ByteString longHead_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 长连接包头
     * </pre>
     *
     * <code>bytes longHead = 7;</code>
     */
    public com.google.protobuf.ByteString getLongHead() {
      return longHead_;
    }
    /**
     * <pre>
     * 长连接包头
     * </pre>
     *
     * <code>bytes longHead = 7;</code>
     */
    public Builder setLongHead(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      longHead_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 长连接包头
     * </pre>
     *
     * <code>bytes longHead = 7;</code>
     */
    public Builder clearLongHead() {
      
      longHead_ = getDefaultInstance().getLongHead();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString payloads_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>bytes payloads = 8;</code>
     */
    public com.google.protobuf.ByteString getPayloads() {
      return payloads_;
    }
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>bytes payloads = 8;</code>
     */
    public Builder setPayloads(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payloads_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>bytes payloads = 8;</code>
     */
    public Builder clearPayloads() {
      
      payloads_ = getDefaultInstance().getPayloads();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString playloadextend_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 扩展数据
     * </pre>
     *
     * <code>bytes playloadextend = 9;</code>
     */
    public com.google.protobuf.ByteString getPlayloadextend() {
      return playloadextend_;
    }
    /**
     * <pre>
     * 扩展数据
     * </pre>
     *
     * <code>bytes playloadextend = 9;</code>
     */
    public Builder setPlayloadextend(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      playloadextend_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 扩展数据
     * </pre>
     *
     * <code>bytes playloadextend = 9;</code>
     */
    public Builder clearPlayloadextend() {
      
      playloadextend_ = getDefaultInstance().getPlayloadextend();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BaseMsg)
  }

  // @@protoc_insertion_point(class_scope:BaseMsg)
  private static final com.wx.frameWork.proto.BaseMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wx.frameWork.proto.BaseMsg();
  }

  public static com.wx.frameWork.proto.BaseMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BaseMsg>
      PARSER = new com.google.protobuf.AbstractParser<BaseMsg>() {
    public BaseMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BaseMsg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BaseMsg> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BaseMsg> getParserForType() {
    return PARSER;
  }

  public com.wx.frameWork.proto.BaseMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

