// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WechatProto.proto

package com.wx.frameWork.proto;

/**
 * <pre>
 * 完整的grpc结构体
 * </pre>
 *
 * Protobuf type {@code WechatMsg}
 */
public  final class WechatMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WechatMsg)
    WechatMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WechatMsg.newBuilder() to construct.
  private WechatMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WechatMsg() {
    token_ = "";
    version_ = "";
    timeStamp_ = 0;
    iP_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WechatMsg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.wx.frameWork.proto.BaseMsg.Builder subBuilder = null;
            if (baseMsg_ != null) {
              subBuilder = baseMsg_.toBuilder();
            }
            baseMsg_ = input.readMessage(com.wx.frameWork.proto.BaseMsg.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(baseMsg_);
              baseMsg_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            token_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 32: {

            timeStamp_ = input.readInt32();
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            iP_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wx.frameWork.proto.WechatProto.internal_static_WechatMsg_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wx.frameWork.proto.WechatProto.internal_static_WechatMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wx.frameWork.proto.WechatMsg.class, com.wx.frameWork.proto.WechatMsg.Builder.class);
  }

  public static final int BASEMSG_FIELD_NUMBER = 1;
  private com.wx.frameWork.proto.BaseMsg baseMsg_;
  /**
   * <pre>
   * 请求消息结构体
   * </pre>
   *
   * <code>.BaseMsg baseMsg = 1;</code>
   */
  public boolean hasBaseMsg() {
    return baseMsg_ != null;
  }
  /**
   * <pre>
   * 请求消息结构体
   * </pre>
   *
   * <code>.BaseMsg baseMsg = 1;</code>
   */
  public com.wx.frameWork.proto.BaseMsg getBaseMsg() {
    return baseMsg_ == null ? com.wx.frameWork.proto.BaseMsg.getDefaultInstance() : baseMsg_;
  }
  /**
   * <pre>
   * 请求消息结构体
   * </pre>
   *
   * <code>.BaseMsg baseMsg = 1;</code>
   */
  public com.wx.frameWork.proto.BaseMsgOrBuilder getBaseMsgOrBuilder() {
    return getBaseMsg();
  }

  public static final int TOKEN_FIELD_NUMBER = 2;
  private volatile Object token_;
  /**
   * <pre>
   * 授权TOKEN,CODE,V3_
   * </pre>
   *
   * <code>string token = 2;</code>
   */
  public String getToken() {
    Object ref = token_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 授权TOKEN,CODE,V3_
   * </pre>
   *
   * <code>string token = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTokenBytes() {
    Object ref = token_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 3;
  private volatile Object version_;
  /**
   * <pre>
   * 协议版本
   * </pre>
   *
   * <code>string version = 3;</code>
   */
  public String getVersion() {
    Object ref = version_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 协议版本
   * </pre>
   *
   * <code>string version = 3;</code>
   */
  public com.google.protobuf.ByteString
      getVersionBytes() {
    Object ref = version_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private int timeStamp_;
  /**
   * <pre>
   * 消息时间戳
   * </pre>
   *
   * <code>int32 timeStamp = 4;</code>
   */
  public int getTimeStamp() {
    return timeStamp_;
  }

  public static final int IP_FIELD_NUMBER = 5;
  private volatile Object iP_;
  /**
   * <pre>
   * 外网 IP
   * </pre>
   *
   * <code>string iP = 5;</code>
   */
  public String getIP() {
    Object ref = iP_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      iP_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 外网 IP
   * </pre>
   *
   * <code>string iP = 5;</code>
   */
  public com.google.protobuf.ByteString
      getIPBytes() {
    Object ref = iP_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      iP_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (baseMsg_ != null) {
      output.writeMessage(1, getBaseMsg());
    }
    if (!getTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
    }
    if (!getVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, version_);
    }
    if (timeStamp_ != 0) {
      output.writeInt32(4, timeStamp_);
    }
    if (!getIPBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, iP_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (baseMsg_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseMsg());
    }
    if (!getTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
    }
    if (!getVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, version_);
    }
    if (timeStamp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, timeStamp_);
    }
    if (!getIPBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, iP_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wx.frameWork.proto.WechatMsg)) {
      return super.equals(obj);
    }
    com.wx.frameWork.proto.WechatMsg other = (com.wx.frameWork.proto.WechatMsg) obj;

    boolean result = true;
    result = result && (hasBaseMsg() == other.hasBaseMsg());
    if (hasBaseMsg()) {
      result = result && getBaseMsg()
          .equals(other.getBaseMsg());
    }
    result = result && getToken()
        .equals(other.getToken());
    result = result && getVersion()
        .equals(other.getVersion());
    result = result && (getTimeStamp()
        == other.getTimeStamp());
    result = result && getIP()
        .equals(other.getIP());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseMsg()) {
      hash = (37 * hash) + BASEMSG_FIELD_NUMBER;
      hash = (53 * hash) + getBaseMsg().hashCode();
    }
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimeStamp();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIP().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wx.frameWork.proto.WechatMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wx.frameWork.proto.WechatMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wx.frameWork.proto.WechatMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wx.frameWork.proto.WechatMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wx.frameWork.proto.WechatMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wx.frameWork.proto.WechatMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wx.frameWork.proto.WechatMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wx.frameWork.proto.WechatMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wx.frameWork.proto.WechatMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wx.frameWork.proto.WechatMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wx.frameWork.proto.WechatMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wx.frameWork.proto.WechatMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wx.frameWork.proto.WechatMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 完整的grpc结构体
   * </pre>
   *
   * Protobuf type {@code WechatMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WechatMsg)
      com.wx.frameWork.proto.WechatMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wx.frameWork.proto.WechatProto.internal_static_WechatMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wx.frameWork.proto.WechatProto.internal_static_WechatMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wx.frameWork.proto.WechatMsg.class, com.wx.frameWork.proto.WechatMsg.Builder.class);
    }

    // Construct using com.wx.frameWork.proto.WechatMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (baseMsgBuilder_ == null) {
        baseMsg_ = null;
      } else {
        baseMsg_ = null;
        baseMsgBuilder_ = null;
      }
      token_ = "";

      version_ = "";

      timeStamp_ = 0;

      iP_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wx.frameWork.proto.WechatProto.internal_static_WechatMsg_descriptor;
    }

    public com.wx.frameWork.proto.WechatMsg getDefaultInstanceForType() {
      return com.wx.frameWork.proto.WechatMsg.getDefaultInstance();
    }

    public com.wx.frameWork.proto.WechatMsg build() {
      com.wx.frameWork.proto.WechatMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.wx.frameWork.proto.WechatMsg buildPartial() {
      com.wx.frameWork.proto.WechatMsg result = new com.wx.frameWork.proto.WechatMsg(this);
      if (baseMsgBuilder_ == null) {
        result.baseMsg_ = baseMsg_;
      } else {
        result.baseMsg_ = baseMsgBuilder_.build();
      }
      result.token_ = token_;
      result.version_ = version_;
      result.timeStamp_ = timeStamp_;
      result.iP_ = iP_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wx.frameWork.proto.WechatMsg) {
        return mergeFrom((com.wx.frameWork.proto.WechatMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wx.frameWork.proto.WechatMsg other) {
      if (other == com.wx.frameWork.proto.WechatMsg.getDefaultInstance()) return this;
      if (other.hasBaseMsg()) {
        mergeBaseMsg(other.getBaseMsg());
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (other.getTimeStamp() != 0) {
        setTimeStamp(other.getTimeStamp());
      }
      if (!other.getIP().isEmpty()) {
        iP_ = other.iP_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wx.frameWork.proto.WechatMsg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wx.frameWork.proto.WechatMsg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.wx.frameWork.proto.BaseMsg baseMsg_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wx.frameWork.proto.BaseMsg, com.wx.frameWork.proto.BaseMsg.Builder, com.wx.frameWork.proto.BaseMsgOrBuilder> baseMsgBuilder_;
    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     *
     * <code>.BaseMsg baseMsg = 1;</code>
     */
    public boolean hasBaseMsg() {
      return baseMsgBuilder_ != null || baseMsg_ != null;
    }
    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     *
     * <code>.BaseMsg baseMsg = 1;</code>
     */
    public com.wx.frameWork.proto.BaseMsg getBaseMsg() {
      if (baseMsgBuilder_ == null) {
        return baseMsg_ == null ? com.wx.frameWork.proto.BaseMsg.getDefaultInstance() : baseMsg_;
      } else {
        return baseMsgBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     *
     * <code>.BaseMsg baseMsg = 1;</code>
     */
    public Builder setBaseMsg(com.wx.frameWork.proto.BaseMsg value) {
      if (baseMsgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseMsg_ = value;
        onChanged();
      } else {
        baseMsgBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     *
     * <code>.BaseMsg baseMsg = 1;</code>
     */
    public Builder setBaseMsg(
        com.wx.frameWork.proto.BaseMsg.Builder builderForValue) {
      if (baseMsgBuilder_ == null) {
        baseMsg_ = builderForValue.build();
        onChanged();
      } else {
        baseMsgBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     *
     * <code>.BaseMsg baseMsg = 1;</code>
     */
    public Builder mergeBaseMsg(com.wx.frameWork.proto.BaseMsg value) {
      if (baseMsgBuilder_ == null) {
        if (baseMsg_ != null) {
          baseMsg_ =
            com.wx.frameWork.proto.BaseMsg.newBuilder(baseMsg_).mergeFrom(value).buildPartial();
        } else {
          baseMsg_ = value;
        }
        onChanged();
      } else {
        baseMsgBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     *
     * <code>.BaseMsg baseMsg = 1;</code>
     */
    public Builder clearBaseMsg() {
      if (baseMsgBuilder_ == null) {
        baseMsg_ = null;
        onChanged();
      } else {
        baseMsg_ = null;
        baseMsgBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     *
     * <code>.BaseMsg baseMsg = 1;</code>
     */
    public com.wx.frameWork.proto.BaseMsg.Builder getBaseMsgBuilder() {
      
      onChanged();
      return getBaseMsgFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     *
     * <code>.BaseMsg baseMsg = 1;</code>
     */
    public com.wx.frameWork.proto.BaseMsgOrBuilder getBaseMsgOrBuilder() {
      if (baseMsgBuilder_ != null) {
        return baseMsgBuilder_.getMessageOrBuilder();
      } else {
        return baseMsg_ == null ?
            com.wx.frameWork.proto.BaseMsg.getDefaultInstance() : baseMsg_;
      }
    }
    /**
     * <pre>
     * 请求消息结构体
     * </pre>
     *
     * <code>.BaseMsg baseMsg = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wx.frameWork.proto.BaseMsg, com.wx.frameWork.proto.BaseMsg.Builder, com.wx.frameWork.proto.BaseMsgOrBuilder> 
        getBaseMsgFieldBuilder() {
      if (baseMsgBuilder_ == null) {
        baseMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.wx.frameWork.proto.BaseMsg, com.wx.frameWork.proto.BaseMsg.Builder, com.wx.frameWork.proto.BaseMsgOrBuilder>(
                getBaseMsg(),
                getParentForChildren(),
                isClean());
        baseMsg_ = null;
      }
      return baseMsgBuilder_;
    }

    private Object token_ = "";
    /**
     * <pre>
     * 授权TOKEN,CODE,V3_
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 授权TOKEN,CODE,V3_
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 授权TOKEN,CODE,V3_
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public Builder setToken(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 授权TOKEN,CODE,V3_
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public Builder clearToken() {
      
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 授权TOKEN,CODE,V3_
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      token_ = value;
      onChanged();
      return this;
    }

    private Object version_ = "";
    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    public Builder setVersion(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private int timeStamp_ ;
    /**
     * <pre>
     * 消息时间戳
     * </pre>
     *
     * <code>int32 timeStamp = 4;</code>
     */
    public int getTimeStamp() {
      return timeStamp_;
    }
    /**
     * <pre>
     * 消息时间戳
     * </pre>
     *
     * <code>int32 timeStamp = 4;</code>
     */
    public Builder setTimeStamp(int value) {
      
      timeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息时间戳
     * </pre>
     *
     * <code>int32 timeStamp = 4;</code>
     */
    public Builder clearTimeStamp() {
      
      timeStamp_ = 0;
      onChanged();
      return this;
    }

    private Object iP_ = "";
    /**
     * <pre>
     * 外网 IP
     * </pre>
     *
     * <code>string iP = 5;</code>
     */
    public String getIP() {
      Object ref = iP_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        iP_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 外网 IP
     * </pre>
     *
     * <code>string iP = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIPBytes() {
      Object ref = iP_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        iP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 外网 IP
     * </pre>
     *
     * <code>string iP = 5;</code>
     */
    public Builder setIP(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iP_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 外网 IP
     * </pre>
     *
     * <code>string iP = 5;</code>
     */
    public Builder clearIP() {
      
      iP_ = getDefaultInstance().getIP();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 外网 IP
     * </pre>
     *
     * <code>string iP = 5;</code>
     */
    public Builder setIPBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iP_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WechatMsg)
  }

  // @@protoc_insertion_point(class_scope:WechatMsg)
  private static final com.wx.frameWork.proto.WechatMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wx.frameWork.proto.WechatMsg();
  }

  public static com.wx.frameWork.proto.WechatMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WechatMsg>
      PARSER = new com.google.protobuf.AbstractParser<WechatMsg>() {
    public WechatMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WechatMsg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WechatMsg> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<WechatMsg> getParserForType() {
    return PARSER;
  }

  public com.wx.frameWork.proto.WechatMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

